import {ACTIONS,NEEDS,freshState,step,feedback,probabilities,activeMask,features,saveBrain,restoreBrain,decodeState,evaluate} from './brain.js';
const $=id=>document.getElementById(id),KEY='fly-house-world-v1';
let state=freshState(),storageOK=true,paused=false,speed=1,elapsed=0,lastFrame=0,toastTimer,feedbackPulse=0,frameNo=0;
try{const stored=localStorage.getItem(KEY);if(stored){const decoded=decodeState(stored);if(decoded)state=decoded;else setTimeout(()=>toast('An unreadable save was replaced with a fresh world.'),500);}}catch{storageOK=false;}
const time=m=>`${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(Math.floor(m)%60).padStart(2,'0')}`;
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3200);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}$('save-status').textContent=storageOK?'Saved on this browser':'Saving unavailable';$('storage-note').textContent=storageOK?'Progress stays in this browser.':'Storage unavailable — this session will not be saved.';}
function log(text,detail='',icon='✦',reward=0){state.journal.unshift({text,detail,icon,reward,minute:state.minutes});state.journal=state.journal.slice(0,12);}
const needEls=NEEDS.map((n,i)=>{const node=document.createElement('div');node.className='need';node.style.setProperty('--need-color',n.color);node.innerHTML=`<div class="need-heading"><span>${n.name}</span><b></b></div><div class="need-track" role="meter" aria-label="${n.name}" aria-valuemin="0" aria-valuemax="100"><span></span></div>`;$('needs').append(node);return node;});
const policyEls=ACTIONS.map(a=>{const n=document.createElement('div');n.className='policy-row';n.innerHTML=`<span>${a.name}</span><div class="policy-track"><span></span></div><strong></strong>`;$('policy-bars').append(n);return n;});
const roomEls=ACTIONS.map((a,i)=>{const b=document.createElement('button');b.className='room-hotspot';b.setAttribute('aria-label',`${a.room}: suggest ${a.name.toLowerCase()}`);b.innerHTML=`<span class="room-label">${a.icon} ${a.room}<small>Suggest ${a.name.toLowerCase()}</small></span>`;b.onclick=()=>doStep(i);$('room-grid').append(b);return b;});
function doStep(forced=null){const choice=step(state,forced);const a=ACTIONS[choice.action];log(a.activity,forced!==null?'You suggested this activity.':(Math.max(...probabilities(state))<.27?'Trying something out.':'Chosen from its needs and learned preferences.'),a.icon,choice.reward);render();persist();elapsed=0;}
function render(){const day=Math.floor(state.minutes/1440)+1,hour=Math.floor(state.minutes/60)%24;$('clock').textContent=time(state.minutes);$('day').textContent=`DAY ${String(day).padStart(2,'0')}`;$('sky-icon').textContent=hour>=19||hour<6?'☾':'☀';$('experiences').textContent=state.steps.toLocaleString();$('link-count').textContent=activeMask(state.damage).flat().filter(Boolean).length;$('update-count').textContent=state.updates.toLocaleString();$('reward-total').textContent=state.totalReward.toFixed(1);$('learning').checked=state.learning;$('damage').value=state.damage;$('damage-value').textContent=state.damage+'%';$('restore-brain').disabled=!state.checkpoint;$('checkpoint-status').textContent=state.checkpoint?`Brain saved after ${state.checkpoint.steps} experiences. Restore also reconnects all weights.`:'No brain checkpoint yet.';$('reward').disabled=$('discourage').disabled=!state.learning||!state.last;
 needEls.forEach((n,i)=>{const v=Math.round(state.needs[i]*100);n.querySelector('b').textContent=v;n.querySelector('.need-track>span').style.width=v+'%';n.querySelector('[role=meter]').setAttribute('aria-valuenow',v);});
 const probs=probabilities(state);policyEls.forEach((n,i)=>{n.querySelector('.policy-track>span').style.width=(probs[i]*100)+'%';n.querySelector('strong').textContent=Math.round(probs[i]*100)+'%';});
 if(state.last){const a=ACTIONS[state.last.action];$('activity').textContent=a.activity;$('decision').textContent=state.last.forced?'Following your suggestion.':state.learning?'Choosing, experiencing, learning.':'Learning paused. Learned preferences still guide choices.';$('fly').style.left=a.x+'%';$('fly').style.top=a.y+'%';$('fly').classList.toggle('sleeping',a.id==='sleep');$('fly-thought').textContent=a.thought;roomEls.forEach((b,i)=>{b.classList.toggle('selected',i===state.last.action);b.setAttribute('aria-pressed',i===state.last.action);});}else{$('activity').textContent='Exploring the house';$('decision').textContent='Deciding what to do next…';$('fly-thought').textContent='Making myself at home.';roomEls.forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false');});}
 $('journal').replaceChildren();for(const e of state.journal.slice(0,5)){const li=document.createElement('li');li.className='journal-entry';const tm=document.createElement('span');tm.className='journal-time';tm.textContent=time(e.minute);const icon=document.createElement('span');icon.className='journal-icon';icon.textContent=e.icon;const p=document.createElement('p');p.textContent=e.text;const small=document.createElement('small');small.textContent=e.detail;p.append(small);const rw=document.createElement('span');rw.className='journal-reward'+(e.reward<0?' negative':'');rw.textContent=e.reward?(e.reward>0?'+':'')+e.reward.toFixed(2):'';li.append(tm,icon,p,rw);$('journal').append(li);}drawBrain();}
function setPause(value){paused=!!value;$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Resume simulation':'Pause simulation');$('pause').title=paused?'Resume simulation':'Pause simulation';$('world-status').textContent=paused?'A moment of stillness':'Life is happening';$('live-dot').classList.toggle('paused',paused);}
function giveFeedback(value){try{const a=feedback(state,value);feedbackPulse=1;log(value>0?'A little encouragement.':'A choice to reconsider.',`${ACTIONS[a].name} received ${value>0?'positive':'negative'} feedback.`,value>0?'✦':'−',value);$('reward-flash').textContent=value>0?'+ reward received':'− feedback received';toast(value>0?`Rewarded: ${ACTIONS[a].name}. Its learned weights changed.`:`Discouraged: ${ACTIONS[a].name}. Its learned weights changed.`);render();persist();}catch(e){toast(e.message);}}
function setDamage(value){if(!Number.isFinite(value)||value<0||value>80)throw new Error('Damage must be between 0 and 80.');state.damage=value;render();persist();}
function checkpoint(){saveBrain(state);log('A little mind, remembered.','Saved a checkpoint of Pip’s learned weights.','↓');render();persist();toast('Brain checkpoint saved on this browser.');}
function restore(){try{restoreBrain(state);log('Back to a familiar mind.','Learned weights restored. All links reconnected.','↺');elapsed=0;render();persist();toast('Brain restored. The day continues.');}catch(e){toast(e.message);}}
function reset(){state=freshState();elapsed=0;feedbackPulse=0;$('fly').style.left='48%';$('fly').style.top='45%';$('fly').classList.remove('sleeping');$('benchmark-result').hidden=true;log('Pip moved into a human house.','A fresh brain. A whole house to explore.','🪰');setPause(false);render();persist();}
$('pause').onclick=()=>setPause(!paused);document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{speed=Number(b.dataset.speed);document.querySelectorAll('[data-speed]').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-pressed',n===b);});$('fly').style.transitionDuration=(speed===1?1.4:speed===5?.45:.12)+'s';});
$('focus').onclick=()=>{const active=document.body.classList.toggle('expanded');$('focus').setAttribute('aria-label',active?'Restore standard view':'Expand house view');drawBrain();};
$('reward').onclick=()=>giveFeedback(1.5);$('discourage').onclick=()=>giveFeedback(-1);$('learning').onchange=e=>{state.learning=e.target.checked;log(state.learning?'Learning switched on.':'Learning switched off.',state.learning?'New experiences can change the weights.':'Choices continue; weights stay fixed.','⌁');render();persist();};
$('damage').oninput=e=>setDamage(Number(e.target.value));$('damage').onchange=()=>{log(`${state.damage}% of weights disconnected.`,'Disabled links stop influencing choices and learning.','⌘');render();persist();};$('save-brain').onclick=checkpoint;$('restore-brain').onclick=restore;
let beforeDialog=false;function openGuide(){beforeDialog=paused;setPause(true);$('guide').showModal();}$('guide-button').onclick=$('model-button').onclick=openGuide;document.querySelector('.dialog-close').onclick=document.querySelector('.dialog-done').onclick=()=>$('guide').close();$('guide').addEventListener('close',()=>setPause(beforeDialog));let beforeReset=false;$('reset-button').onclick=()=>{beforeReset=paused;setPause(true);$('reset-dialog').showModal();};$('cancel-reset').onclick=()=>$('reset-dialog').close();let didReset=false;$('confirm-reset').onclick=()=>{didReset=true;reset();$('reset-dialog').close();};$('reset-dialog').addEventListener('close',()=>{if(!didReset)setPause(beforeReset);didReset=false;});
$('benchmark').onclick=()=>{const b=$('benchmark');b.disabled=true;b.textContent='Comparing fixed brains…';setTimeout(()=>{try{const untrained=evaluate(freshState().weights),intact=evaluate(state.weights),damaged=evaluate(state.weights,state.damage);const box=$('benchmark-result');box.hidden=false;box.replaceChildren();const title=document.createElement('strong');title.textContent='Same starting conditions. No learning during tests.';box.append(title);const table=document.createElement('table');table.innerHTML='<thead><tr><th>Brain</th><th>Wellbeing</th><th>Critical needs</th></tr></thead>';const tbody=document.createElement('tbody');[['Untrained',untrained],['Your learned brain',intact],[`With ${state.damage}% disconnected`,damaged]].forEach(([name,v])=>{const tr=document.createElement('tr');[name,v.wellness.toFixed(1)+'%',v.critical.toFixed(1)+'%'].forEach(text=>{const td=document.createElement('td');td.textContent=text;tr.append(td);});tbody.append(tr);});table.append(tbody);box.append(table);const p=document.createElement('p');p.textContent='8 matched trials × 180 choices. Wellbeing is mean need satisfaction; critical needs is the share of steps with any need below 15%. This evaluates the current weights, not biological fidelity. More experience does not guarantee improvement.';box.append(p);}finally{b.disabled=false;b.innerHTML='Run learning comparison <span>↗</span>';}},40);};
function drawBrain(){const canvas=$('brain-canvas'),w=canvas.clientWidth,h=135;if(!w)return;const dpr=Math.min(window.devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);const mask=activeMask(state.damage),f=features(state.needs),p=probabilities(state),left=Array.from({length:6},(_,i)=>({x:25,y:15+i*21})),right=Array.from({length:6},(_,i)=>({x:w-25,y:15+i*21}));for(let a=0;a<6;a++)for(let j=0;j<6;j++){if(!mask[a][j])continue;const weight=state.weights[a][j],strength=Math.min(Math.abs(weight)/2,1);c.beginPath();c.moveTo(left[j].x,left[j].y);c.bezierCurveTo(w*.45,left[j].y,w*.55,right[a].y,right[a].x,right[a].y);c.strokeStyle=weight<0?`rgba(246,168,141,${.07+strength*.48})`:`rgba(171,156,237,${.10+strength*.65})`;c.lineWidth=.5+strength*1.5;c.stroke();}for(let j=0;j<6;j++){const pt=left[j];c.fillStyle=`rgba(196,244,129,${.3+f[j]*.7})`;c.beginPath();c.arc(pt.x,pt.y,3+f[j]*2,0,Math.PI*2);c.fill();}for(let a=0;a<6;a++){const pt=right[a],on=state.last?.action===a;c.shadowBlur=on?10+feedbackPulse*12:0;c.shadowColor=feedbackPulse?'#c4f481':'#f6a88d';c.fillStyle=on?'#f6c2a9':'#ab8d83';c.beginPath();c.arc(pt.x,pt.y,on?5:3,0,Math.PI*2);c.fill();c.shadowBlur=0;}if(state.last){const t=(frameNo%120)/120,src=left[1+state.last.action%5],dst=right[state.last.action];c.fillStyle='#e5f8d5';c.beginPath();c.arc(src.x+(dst.x-src.x)*t,src.y+(dst.y-src.y)*t,2,0,Math.PI*2);c.fill();}feedbackPulse=Math.max(0,feedbackPulse-.025);}
function animate(t){const dt=lastFrame?Math.min(t-lastFrame,250):0;lastFrame=t;if(!paused&&!document.hidden){elapsed+=dt*speed;if(elapsed>=6500)doStep();}if(frameNo++%3===0)drawBrain();requestAnimationFrame(animate);}document.addEventListener('visibilitychange',()=>{lastFrame=0;if(document.hidden)persist();});window.addEventListener('pagehide',persist);window.addEventListener('resize',drawBrain);
if(!state.journal.length)log('Pip moved into a human house.','A fresh brain. A whole house to explore.','🪰');render();persist();requestAnimationFrame(animate);
// Optional WebMCP bridge: the same actions as the visible controls.
const context=document.modelContext;if(context?.registerTool){const controller=new AbortController();const reg=(tool)=>{try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}};reg({name:'read_fly_house',title:'Read fly state',description:'Read Pip’s current needs, activity, learning state and damage.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {steps:state.steps,needs:Object.fromEntries(NEEDS.map((n,i)=>[n.name,state.needs[i]])),action:state.last?ACTIONS[state.last.action].id:null,learning:state.learning,damage:state.damage};}});reg({name:'suggest_fly_activity',title:'Suggest an activity',description:'Immediately let Pip perform one house activity, updating needs and learning exactly like clicking a room.',inputSchema:{type:'object',properties:{activity:{type:'string',enum:ACTIONS.map(a=>a.id)}},required:['activity'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const i=ACTIONS.findIndex(a=>a.id===input?.activity);if(i<0||Object.keys(input).some(k=>k!=='activity'))throw new Error('Unknown activity');doStep(i);return {activity:ACTIONS[i].id,steps:state.steps};}});window.addEventListener('pagehide',()=>controller.abort(),{once:true});}
