// A deliberately small artificial RL model. No biological connectome data.
export const NEEDS=[{name:'Fullness',color:'#edba7a'},{name:'Energy',color:'#c4f481'},{name:'Hygiene',color:'#83c9e3'},{name:'Joy',color:'#ccabef'},{name:'Purpose',color:'#f5a891'}];
export const ACTIONS=[
 {id:'eat',room:'Kitchen',name:'Eat',icon:'🍊',activity:'Having a little fruit snack',thought:'A crumb is a whole meal.',x:23,y:34,effects:[.56,0,0,.04,0]},
 {id:'play',room:'Living room',name:'Play',icon:'📺',activity:'Watching a very big television',thought:'Just one more episode.',x:51,y:34,effects:[0,-.02,0,.57,0]},
 {id:'sleep',room:'Bedroom',name:'Sleep',icon:'🌙',activity:'Taking a well-earned nap',thought:'Six legs. Zero alarms.',x:79,y:33,effects:[0,.65,-.015,0,0]},
 {id:'wash',room:'Bathroom',name:'Wash',icon:'🫧',activity:'Freshening up all six legs',thought:'Squeaky clean. Mostly.',x:23,y:68,effects:[0,0,.63,.03,0]},
 {id:'work',room:'Study',name:'Work',icon:'💻',activity:'Working on a tiny big idea',thought:'This could have been a buzz.',x:50,y:68,effects:[0,-.06,0,-.04,.66]},
 {id:'garden',room:'Garden',name:'Garden',icon:'🌿',activity:'Tending to the little garden',thought:'A little fresh air.',x:79,y:68,effects:[0,.14,-.025,.20,.17]}
];
export const clamp=(x,lo=0,hi=1)=>Math.max(lo,Math.min(hi,x));
export function seeded(seed=719){return()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;};}
export function freshState(){return {version:1,needs:[.68,.72,.79,.60,.65],weights:Array.from({length:6},()=>Array(6).fill(0)),damage:0,learning:true,steps:0,updates:0,totalReward:0,minutes:360,last:null,journal:[],checkpoint:null,rewards:[]};}
// A nested, reproducible lesion. Raising damage never reconnects a removed edge.
const order=Array.from({length:36},(_,i)=>i);const orderRand=seeded(4317);for(let i=35;i>0;i--){const j=Math.floor(orderRand()*(i+1));[order[i],order[j]]=[order[j],order[i]];}
export function activeMask(damage){const cut=new Set(order.slice(0,Math.round(36*clamp(damage,0,80)/100)));return Array.from({length:6},(_,a)=>Array.from({length:6},(_,f)=>!cut.has(a*6+f)));}
export const features=needs=>[1,...needs.map(n=>(1-n)**2)];
export function qValues(state,needs=state.needs){const f=features(needs),mask=activeMask(state.damage);return state.weights.map((row,a)=>row.reduce((s,w,j)=>s+(mask[a][j]?w*f[j]:0),0));}
export function probabilities(state,needs=state.needs){const q=qValues(state,needs),m=Math.max(...q),e=q.map(v=>Math.exp((v-m)/.16)),sum=e.reduce((s,v)=>s+v,0);return e.map(v=>.1/6+.9*v/sum);}
export function choose(state,rng=Math.random){const p=probabilities(state);let r=rng();for(let i=0;i<6;i++){r-=p[i];if(r<=0)return i;}return 5;}
const utility=n=>n.reduce((s,v)=>s+Math.log(.15+v),0);
function update(state,a,f,error){if(!state.learning)return;const mask=activeMask(state.damage),norm=f.reduce((s,v)=>s+v*v,0);for(let j=0;j<6;j++)if(mask[a][j])state.weights[a][j]=clamp(state.weights[a][j]+.18*clamp(error,-4,4)*f[j]/norm,-8,8);state.updates++;}
export function step(state,forced=null,rng=Math.random){if(forced!==null&&(!Number.isInteger(forced)||forced<0||forced>=6))throw new Error('Unknown action');const before=[...state.needs],a=forced??choose(state,rng),f=features(before),old=qValues(state,before)[a];const decay=[.047,.055,.042,.052,.045];state.needs=before.map((n,i)=>clamp(n-decay[i]+ACTIONS[a].effects[i]));const reward=(utility(state.needs)-utility(before))*.65-state.needs.filter(v=>v<.15).length*.12;const target=reward+.45*Math.max(...qValues(state));update(state,a,f,target-old);state.steps++;state.minutes+=15;state.totalReward+=reward;state.last={action:a,features:f,reward,forced:forced!==null};state.rewards.push(reward);if(state.rewards.length>100)state.rewards.shift();return state.last;}
export function feedback(state,value){if(!state.last)throw new Error('Let Pip make a choice first.');if(!state.learning)throw new Error('Turn learning on to give feedback.');if(!Number.isFinite(value)||Math.abs(value)>2)throw new Error('Invalid feedback');update(state,state.last.action,state.last.features,value);state.totalReward+=value;return state.last.action;}
export function saveBrain(state){state.checkpoint={weights:state.weights.map(r=>[...r]),updates:state.updates,steps:state.steps,savedAt:Date.now()};}
export function restoreBrain(state){if(!state.checkpoint)throw new Error('Save a brain first.');state.weights=state.checkpoint.weights.map(r=>[...r]);state.damage=0;state.last=null;}
const validMatrix=m=>Array.isArray(m)&&m.length===6&&m.every(r=>Array.isArray(r)&&r.length===6&&r.every(v=>Number.isFinite(v)&&Math.abs(v)<=8));
export function decodeState(raw){try{const d=typeof raw==='string'?JSON.parse(raw):raw;if(!d||d.version!==1||!validMatrix(d.weights)||!Array.isArray(d.needs)||d.needs.length!==5||!d.needs.every(x=>Number.isFinite(x)&&x>=0&&x<=1)||![d.minutes,d.steps,d.updates,d.totalReward,d.damage].every(Number.isFinite)||d.steps<0||d.updates<0||d.minutes<0||d.damage<0||d.damage>80)return null;const s={...freshState(),...d,learning:!!d.learning};s.journal=Array.isArray(d.journal)?d.journal.filter(v=>v&&typeof v.text==='string'&&typeof v.detail==='string'&&typeof v.icon==='string'&&Number.isFinite(v.minute)&&Number.isFinite(v.reward)).slice(0,12):[];s.rewards=Array.isArray(d.rewards)?d.rewards.filter(Number.isFinite).slice(-100):[];s.checkpoint=d.checkpoint&&validMatrix(d.checkpoint.weights)&&[d.checkpoint.steps,d.checkpoint.updates,d.checkpoint.savedAt].every(Number.isFinite)?d.checkpoint:null;s.last=d.last&&Number.isInteger(d.last.action)&&d.last.action>=0&&d.last.action<6&&Array.isArray(d.last.features)&&d.last.features.length===6&&d.last.features.every(Number.isFinite)&&Number.isFinite(d.last.reward)?d.last:null;return s;}catch{return null;}}
export function evaluate(weights,damage=0){let wellness=0,critical=0,reward=0;const trials=8,steps=180;for(let trial=0;trial<trials;trial++){const rng=seeded(1234+trial),s=freshState();s.weights=weights.map(r=>[...r]);s.damage=damage;s.learning=false;s.needs=s.needs.map(()=>.35+rng()*.5);for(let t=0;t<steps;t++){step(s,null,rng);wellness+=s.needs.reduce((a,b)=>a+b,0)/5;critical+=s.needs.some(v=>v<.15)?1:0;}reward+=s.totalReward;}return {wellness:wellness/(trials*steps)*100,critical:critical/(trials*steps)*100,reward:reward/(trials*steps),trials,steps};}
