// manifest.ts — load assets.json once on bootup; expose a tiny helper
// that appends `?v=<sha>` to asset URLs so the browser cache key is
// unique per build.
//
// Pairs with `Cache-Control: public, max-age=31536000, immutable` on
// the binaries (set by tools/upload_to_r2.sh) — gives permanent browser
// caching with automatic invalidation on rebuild. No IDB, no service
// worker, just HTTP semantics.
//
// Generated by tools/write_manifest.py, refreshed after any
// build_csr.py / build_vnc.py / extract_walking_policy.py /
// dump_flybody_spec.py run.

export type VersionFor = (filename: string) => string;

const NOOP: VersionFor = () => "";

/** Fetch /assets.json (or VITE_ASSET_MANIFEST_URL) and return a closure
 * that maps a filename → "?v=<sha>" suffix. If the manifest is missing
 * (local dev before first build, or 404 on R2) the closure returns ""
 * and URLs load unversioned — fine, just no cache busting. */
export async function loadManifest(
  url: string = (import.meta.env.VITE_ASSET_MANIFEST_URL ?? "/assets.json"),
): Promise<VersionFor> {
  let manifest: Record<string, string> = {};
  try {
    const r = await fetch(url, { cache: "no-cache", signal: AbortSignal.timeout(10_000) });
    if (r.ok) manifest = await r.json();
  } catch {
    return NOOP;
  }
  return (filename: string) => {
    const v = manifest[filename];
    return v ? `?v=${v}` : "";
  };
}
